### ISSUE TITLE
Support for RHEL8/AL3 scheduler and updated mappings in installer /default_config.yml

### ISSUE THREAD

**Issue by tammy-ruby-cherry** [awslabs/scale-out-computing-on-aws#106]
**Describe the feature you'd like**
The current SOCA repo (2.7.4)  has scheduler options for only for AL2, Centos7, and RHEL7 only.  

1. Has SOCA been tested with AL3 or RHEL8?
2. Are there plans to update installer/default_config.yml  mappings to include AL3, RHEL8?

Thanks!
Tammy

**Comment by jsynack** [comment]
Hello @tammy-ruby-cherry ,

Thank-you for the feature request!

For you specific items:

o `Amazon Linux 2023` -  Currently does not support `FSx/Lustre` filesystems or GUIs (as of Dec-2023).

In `SOCA 2.7.5` - You will have the ability to deploy `AmazonLinux2023` but you will not have the ability to mount FSx/Lustre filesystems or use a VDI/GUI due to these limitations.

(`SOCA 2.7.5` is expected around EOY 2023)

Future enablement for FSx/L on `AmazonLinux2023` will require a patch/point release to enable once it makes it into the `AmazonLinux2023` support list. (it is on the way)

For additional BaseOSes - yes - we have some internal recipes that work with newer versions of RHEL (8/9) and are making SOCA updates for this (expected to be early in 2024). If you have specific requirements of the BaseOSes , please let us know.

We will leave this issue open to continue to track the requests for `AL2023` and `RHEL8/9`.

**Comment by tammy-ruby-cherry** [comment]
Hey,

Checking in again about support for RHEL8.    I understand that SOCA 2.7.5 will be released shortly--will this update be included?

Thanks,
Tammy

**Comment by mcrozes** [comment]
Hello @tammy-ruby-cherry  -

Next version of SOCA will support RHEL8/RHEL9 and Rocky8/Rocky9. Feel free to email me if you want additional details!
