### ISSUE TITLE
Unable to start desktop

### ISSUE THREAD

**Issue by tian3323106** [awslabs/scale-out-computing-on-aws#140]
Hello I got the following message when I launch the session 1. I think I killed my previous session 1. I have no issue to launch session 2. Thank you for your help.

Unable to start desktop due to: Error while trying to provision soca-qht-green-LinuxDesktop1-tianleix due to An error occurred (AlreadyExistsException) when calling the CreateStack operation: Stack [soca-qht-green-LinuxDesktop1-tianleix] already exists.

**Comment by mcrozes** [comment]
Hello @tian3323106  -

You cannot launch your desktop because you already have one using the same name. 

- If you just killed your previous session:  You may need to wait a couple of minutes to make sure the associated CloudFormation stack is removed.
- If you killed your previous session > 10 minutes ago and still can't launch a new desktop: Connect to CloudFormation and delete the stack manually. You can also check the CloudFormation logs to understand why your Stack was not delete automatically.

Another option is to simply change the Session Name of your Virtual Desktop as mentioned on https://awslabs.github.io/scale-out-computing-on-aws/web-interface/create-virtual-desktops/

**Comment by mcrozes** [comment]
If your CloudFormation is stuck in ROLLBACK/DELETE_FAILED, you will have to access the AWS Console and remove the Stack directly from there. I will go ahead and close this ticket and follow-up with you directly via email
