### ISSUE TITLE
alwayson queue is created by Scheduler.sh but does not exist in queue_mapping.yml

### ISSUE THREAD

**Issue by gwolski** [awslabs/scale-out-computing-on-aws#69]
Version: 2.7.0

alwayson queue is created at line 283 of source/scripts/Scheduler.sh.
The documentation describes this as  a default queue that will always be created (along with other queues):
https://awslabs.github.io/scale-out-computing-on-aws/web-interface/create-your-own-queue/

However, the source/scripts/SchedulerPostReboot.sh does not add the alwayson queue to the /apps/soca/$SOCA_CONFIGURATION/cluster_manager/settings/queue_mapping.yml file.

I would think it should be added?

I'm also trying to figure out the 'workq' - so any insights about this queue would also be appreciated.

**Comment by mcrozes** [comment]
Hello @gwolski  -

As you pointed out, `alwayson` queue is created via https://github.com/awslabs/scale-out-computing-on-aws/blob/main/source/scripts/Scheduler.sh#L283-L287 but not available on the `queue_mapping.yml` file. The reason is queue_mapping is restricted to queue with automatic host provisioning.

Capacity behind the `alwayson` queue must be added/removed manually as the capacity is designed to run 24/7 (or until the relevant stack is deleted). You can get more information https://awslabs.github.io/scale-out-computing-on-aws/tutorials/launch-always-on-instances/#why-alwayson-instances

`workq` is also the default queue created by OpenPBS which is not used nor configured on SOCA.

**Comment by gwolski** [comment]
Thank you for the info.

I forgot to also ask in my original posting - the alwayson queue doesn't seem to have any logs in

/apps/soca/$SOCA_CONFIGURATION/cluster_manager/logs/<queue_name>

Is that an error in my installation or is this intentional?

**Comment by mcrozes** [comment]
> Is that an error in my installation or is this intentional?

There is no `queue_name.log` being created because these logs are limited to the queue configured with "On Demand Provisioning".
If you need to troubleshoot the alwayson queue, I'd first verify whether or not the capacity is being added correctly after executing `add_nodes.py` by running `pbsnodes -a` and verifying whether or not the capacity is registered correctly. At this point you will be able to submit test jobs and use the usual `#PBS -oe` to redirect stdout/err to the location of your choice.

If you need to troubleshoot the scheduling/server piece, logs can be found under `/var/spool/pbs/`

> I was trying to use this queue to debug the use of the flexlm license manager interaction as per the web page: https://awslabs.github.io/scale-out-computing-on-aws/tutorials/job-licenses-flexlm/#test

Is your error related to capacity provisioning or FlexLM? Are you able to submit a test job to the alwayson queue?

**Comment by gwolski** [comment]
I was just following the Test section of the FlexLM setup page:  https://awslabs.github.io/scale-out-computing-on-aws/tutorials/job-licenses-flexlm/#test  and wanted to see the Flex stuff work....

I wanted to see the results of asking for licenses, too many licenses, etc.  Rather than spin up machines I was going to use the alwayson queue.  But as you noted it doesn't put log files in /apps/soca/$SOCA_CONFIGURATION/cluster_manager/logs/<queue_name> so I will use something from an on-demand queue..

I have successfully launched jobs to alwayson as well as to normal queue -- even using a custom ami.  I wanted to use the alwayson queue as I'm trying to track down why it takes 10 minutes for my job to start up after the custom ami has become available...  So I was trying to be "faster" in my debugging by using alwayson.  So now I'm going to debug why my job doesn't start for 10 minutes after my ami is up, then I'll work on FlexLM.... 
Thank you for all the good info.

**Comment by mcrozes** [comment]
To troubleshoot the compute capacity behind the alwayson, you could check `/apps/soca/<YOUR_CLUSTER>/cluster_node_bootstrap/logs/` (https://awslabs.github.io/scale-out-computing-on-aws/troubleshooting/troubleshoot-job-queue/#retrieve-node-logs) and locate the unique ID specific to the capacity provisioning (you can get this information from CloudFormation). This 

If you need any further assistance, I'd recommend reaching out to my email address (my github username @ amazon.com ) as we will be able to better assist you (especially if you need to share your bootstrap logs)
