### ISSUE TITLE
Add support for new region in Hyderabad (ap-south-2)

### ISSUE THREAD

**Issue by cartalla** [awslabs/scale-out-computing-on-aws#90]
**Describe the bug**

When I try to deploy in ap-south-2 I get the following error:

```
Traceback (most recent call last):
  File "cdk_construct.py", line 1078, in <module>
    termination_protection=install_props.Config.termination_protection)
  File "/home/ec2-user/environment/scale-out-computing-on-aws/installer/resources/src/envs/venv-py-installer/lib64/python3.7/site-packages/jsii/_runtime.py", line 86, in __call__
    inst = super().__call__(*args, **kwargs)
  File "cdk_construct.py", line 84, in __init__
    "ami_id": user_specified_variables.custom_ami if user_specified_variables.custom_ami else install_props.RegionMap.__dict__[user_specified_variables.region].__dict__[user_specified_variables.base_os],
KeyError: 'ap-south-2'
```

**To Reproduce**

```
./soca_installer.sh \
--name example-hyd \
--region ap-south-2 \
--bucket semiconductor-core-demos-ap-south-2 \
--ldap-password-file ~/environment/soca-password-admin-hyd.txt \
--ssh-keypair admin-ap-south-2 \
--vpc-cidr 10.4.0.0/16 \
--ldap-user admin \
--base-os centos7 \
--cdk-cmd create \
--skip-config-message
```

**Expected behavior**
Successful deployment

**Please complete the following information about the solution:**
- [ ] Version: d46b9b96f7fe863de9e830d91e35e4f54aa201d5
- [ ] Region: ap-south-2
- [ ] Was the solution modified from the version published on this repository? No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs?

**Comment by jsynack** [comment]
Currently (30 March 2023) the AWS region `ap-south-2` lacks a few services that are required for a SOCA cluster installation/operation.

These services would need to be stubbed out in order to install SOCA into `ap-south-2` in the current form (not just the AMI ID in the mappings).

We will be adding additional configuration knobs to enable/disable these services at installation time in the next SOCA release.

This will allow for installation to proceed into `ap-south-2` while it has additional AWS services activated in-region.
